# Generated by Django 3.2 on 2023-11-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recipes', '0001_initial'),
        ('User_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='User_profile.userprofile')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.recipe')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='User_profile.userprofile')),
            ],
        ),
    ]
