# Generated by Django 4.2.6 on 2023-11-27 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_recipeuserview"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeuserview",
            name="time",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
