# Generated by Django 4.2.6 on 2023-11-27 19:39

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_recipeuserview_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=recipe.models.recipe_directory_path
            ),
        ),
    ]
